### ISSUE TITLE
Adding support for %{count}

### ISSUE THREAD

**Issue by milgner** [shlima/translate_enum#9]
There are some use cases where I'd like to use the `count` functionality so that if you have an enum `model_type` and then you want to show a list of records of model type "Example", you can translate it to "My Examples" - but if there's only one in the list, it would just say "My Example".
 
If there aren't any arguments against it, I'd prepare a PR to enhance the `translated_[enum_attribute]` and corresponding methods with an additional argument to specify `count` (and potentially other arguments, I'd just pass them on to `I18n.t`).

**Comment by shlima** [comment]
Released in version `0.2.0`
